language: generic
install:
script:
- "./build.sh"
env:
  global:
  - secure: uW/DDrfQ98f5pSr3fEno4CFMPzoCX4xEpleHaWGt/HHPRdrzdRKVt31GgFXbCF7BEIP84TxiAJjt5VoqNcbvB+mxMSV0pYCHe+M4nSCCWEGskvRScktdlY2KgjSg2dvK9Cl3sTjWaEHMIlJXfKAT7zPNUCefkvSfL9H696zb6P5HwS4Pa9vcxn0Oko7k+R7BHgt5lcl9lJahvq5NCGp+ERM/0La5x1VCTF+6VwGTh080QjmkYjNKeVQ5XkikkbdW1oIFIdmWbo9/yvAzoTFPCfhSDjScTLH+jll1IJPk8QKtgZTqnO4l9vm2roU+Mho1nreoXNhQw9xiEIET8q0tyE7V2iaOeGEQ+td0wg0LZ5HJyMcF5V8xOZb54uusIuC8x2MSub4jvUZwdN3Ded3WcriVdSNHLNLqWq2gvT+faZnNDmoRrOwJKSlBjB5tJ1PL7SGehbs/LilVCmmr8pPwb1AUWCvv0QJyNSzt1GDGsEnumxO11Oa5ztQvPZTkyr76vUs3GMwh1uQd+QDF00tRHM1N6jfdYMYqOgIbUjzT5OP2z6MRKCjDvZ7WhPPm37MzcFjIoOxVP6eqWS7jpZ+iyAXUnPvShnGs5YVO/oiNf8MtczhjIbPkwqJ8ZR3lL6l3IzrQNtIyjZzt+JaO8askdbMW20rRdqebsM8Po8TBycQ=
